//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stack.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleId { get; set; }
        public int MenuItemId { get; set; }
        public string ArticleName { get; set; }
        public string ArticleNameSeo { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastEditedById { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
    }
}
