//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stack.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PkId { get; set; }
        public string Category { get; set; }
        public string Comment1 { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Pings { get; set; }
        public Nullable<int> UpvoteCount { get; set; }
        public Nullable<bool> UserHasUpvoted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> LastEditedById { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
