//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stack.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public Nullable<int> MenuItemId { get; set; }
        public string ShortContent { get; set; }
        public string Content { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastEditedById { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsPopular { get; set; }
        public string NewsHeadlines { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual Master_Status Master_Status { get; set; }
    }
}
